CREATE DATABASE NewsD;

CREATE SCHEMA Dbo;

CREATE TABLE Dbo.Entity (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(80) NOT NULL,
    PhotoUrl VARCHAR(160) NOT NULL,
    Email VARCHAR(80) NOT NULL,
    Password VARCHAR(80) NOT NULL,
    CreationDate DATETIME NOT NULL,
    LastUpdateDate DATETIME NOT NULL,
    Role INT NOT NULL  
);

CREATE TABLE Dbo.News (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    Likes INT NOT NULL,
    Creator UNIQUEIDENTIFIER NOT NULL
);

ALTER TABLE Dbo.News ADD CONSTRAINT FK_News_Entity FOREIGN KEY (Creator) REFERENCES Dbo.Entity(Id); 

CREATE TABLE Dbo.NewsStatus (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Status INT NOT NULL,
    NewsId UNIQUEIDENTIFIER NOT NULL,
    UpdatedBy UNIQUEIDENTIFIER NOT NULL,
    WhenUpdated DATETIME NOT NULL,
    Reason VARCHAR(300) NOT NULL
);

ALTER TABLE Dbo.NewsStatus ADD CONSTRAINT FK_NewsStatus_Entity FOREIGN KEY (UpdatedBy) REFERENCES Dbo.Entity(Id);
ALTER TABLE Dbo.NewsStatus ADD CONSTRAINT FK_NewsStatus_News FOREIGN KEY (NewsId) REFERENCES Dbo.News(Id);