CREATE TABLE Dbo.NewsStatus (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Status INT NOT NULL,
    NewsId UNIQUEIDENTIFIER NOT NULL,
    UpdatedBy UNIQUEIDENTIFIER NOT NULL,
    WhenUpdated DATETIME NOT NULL,
    Reason VARCHAR(300) NOT NULL
);

ALTER TABLE Dbo.NewsStatus ADD CONSTRAINT FK_NewsStatus_Entity FOREIGN KEY (UpdatedBy) REFERENCES Dbo.Entity(Id);
ALTER TABLE Dbo.NewsStatus ADD CONSTRAINT FK_NewsStatus_News FOREIGN KEY (NewsId) REFERENCES Dbo.News(Id); 